// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fimavazzogjgfnwchxby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbWF2YXp6b2dqZ2Zud2NoeGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTE5MjcsImV4cCI6MjA2ODc2NzkyN30.R1l5GdT1HrSz2Bf1fukDgSYbXNuij0x_u2NTW9QzRME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});